config/routes.rb
Redtracker::Application.routes.draw do
  root :to => "posts#index"

  resources :devs
  resources :posts do
    member do
      get "first_post"
    end
  end

end

app/models/dev.rb
class Dev < ActiveRecord::Base
  attr_accessible :name, :username
  has_many :posts, :dependent => :destroy

  def self.find_or_create name, username=nil
    dev = Dev.where(:name=>name).first
    dev = Dev.create(:name=>name,:username=>username) unless dev
    dev
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :description, :link, :title, :published_at, :dev_id
  attr_taggable :categories
  searchable_on :title,:description,:fp_description

  belongs_to :dev



  scope :newest, order("published_at desc").limit(1)

  def add_categories_from_link! link=nil
    link ||= self.link
    tags = link.split("/")[(4..-3)]
    self.categories = self.categories + tags
    self.categories << "spvp" if link.split("/")[(4..-3)] == ["pvp","pvp"]
  end

  def get_first_post!
    agent = Mechanize.new
    link = self.link.gsub(/[^\/]+\/?$/,"")
    feed = agent.get link
    self.fp_username = feed.search('.post .post-header a.member').first.text
    self.fp_description = fix_links(feed.search('.post .post-body .message-content').first).inner_html
  end

  def get_post_description!
    agent = Mechanize.new
    post_id = self.link.scan(/[^\/]+\/?$/).first
    feed = agent.get self.link
    self.description = fix_links(feed.search("#post#{post_id} .message-content").first).inner_html
    dev_name = feed.search("#post#{post_id} .post-header a.member").first 
    self.dev = Dev.find_or_create(dev_name.text,dev_name["href"])
  end

  def self.get_tags context=nil
    ActiveRecord::Base.connection.execute("select distinct name from taggings join tags on tags.id = taggings.tag_id where taggable_type='Post'#{"AND context='#{context}'" if context};").collect{|t| t["name"]}
  end

  private
  def fix_links nokonode
    nokonode.css("@href,@src").each{|l| l.value="https://forum-en.guildwars2.com"+l.value unless l.value =~ /https?:\/\//i}
    nokonode
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/devs_controller.rb
class DevsController < ApplicationController
  # GET /devs
  # GET /devs.json
  def index
    @devs = Dev.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @devs }
    end
  end

  # GET /devs/1
  # GET /devs/1.json
  def show
    @dev = Dev.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dev }
    end
  end

  # GET /devs/new
  # GET /devs/new.json
  def new
    @dev = Dev.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dev }
    end
  end

  # GET /devs/1/edit
  def edit
    @dev = Dev.find(params[:id])
  end

  # POST /devs
  # POST /devs.json
  def create
    @dev = Dev.new(params[:dev])

    respond_to do |format|
      if @dev.save
        format.html { redirect_to @dev, notice: 'Dev was successfully created.' }
        format.json { render json: @dev, status: :created, location: @dev }
      else
        format.html { render action: "new" }
        format.json { render json: @dev.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /devs/1
  # PUT /devs/1.json
  def update
    @dev = Dev.find(params[:id])

    respond_to do |format|
      if @dev.update_attributes(params[:dev])
        format.html { redirect_to @dev, notice: 'Dev was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dev.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devs/1
  # DELETE /devs/1.json
  def destroy
    @dev = Dev.find(params[:id])
    @dev.destroy

    respond_to do |format|
      format.html { redirect_to devs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("published_at desc")
    @posts = @posts.search_for(params[:q])
    @posts = @posts.tagged_with([params[:categories]], :min=>2, :on=>:categories) if params[:categories]
    @posts = @posts.where(:dev_id=>params[:dev]) if params[:dev]
    @posts = @posts.page(params[:page]).per(25)
    @categories = Post.get_tags 'categories'

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
      format.js {render :partial => "stream", :locals=>{:posts=>@posts}}
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def first_post
    @post = Post.find(params[:id])
    render :text=>@post.fp_description
    # respond_to do |format|
    #   format.json { head @post }
    #   format.js {render :text=>@post.fp_description}
    # end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devs_helper.rb
module DevsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def category_on? categories, tag
     return true if categories.nil?
     categories.include?(tag)
  end
end

app/views/devs/_form.html.haml
= form_for @dev do |f|
  - if @dev.errors.any?
    #error_explanation
      %h2= "#{pluralize(@dev.errors.count, "error")} prohibited this dev from being saved:"
      %ul
        - @dev.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :username
    = f.text_field :username
  .actions
    = f.submit 'Save'

app/views/devs/edit.html.haml
%h1 Editing dev

= render 'form'

= link_to 'Show', @dev
\|
= link_to 'Back', devs_path

app/views/devs/index.html.haml
%h1 Listing devs

%table
  %tr
    %th Name
    %th Username
    %th
    %th
    %th

  - @devs.each do |dev|
    %tr
      %td= dev.name
      %td= dev.username
      %td= link_to 'Show', dev
      %td= link_to 'Edit', edit_dev_path(dev)
      %td= link_to 'Destroy', dev, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Dev', new_dev_path

app/views/devs/new.html.haml
%h1 New dev

= render 'form'

= link_to 'Back', devs_path

app/views/devs/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @dev.name
%p
  %b Username:
  = @dev.username

= link_to 'Edit', edit_dev_path(@dev)
\|
= link_to 'Back', devs_path

app/views/layouts/application.html.haml
!!! 5
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class=\"ie6\" lang=\"en\">
/[if IE 7 ]    <html class=\"ie7\" lang=\"en\">
/[if IE 8 ]    <html class=\"ie8\" lang=\"en\">
/[if IE 9 ]    <html class=\"ie9\" lang=\"en\">
/[if (gt IE 9)|!(IE)] <!--> <html lang=\"en\">

%head
  %meta{ :charset => "utf-8" }

  -# Uncomment to make IE8 render like IE7
  -# meta http-equiv="X-UA-Compatible" content="IE=7"

  -# Set the viewport width to device width for mobile
  %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

  %title
    DevChaser
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "vendor/custom.modernizr"
  = csrf_meta_tags
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-39977856-1', 'devchaser.com');
    ga('send', 'pageview');

%body
  = render "shared/logo_bar"
  %span.notice= notice
  %span.alert= alert
  = yield

  = render "shared/footer"

  = javascript_include_tag "application"

app/views/posts/_categories_sidebar.html.haml
.large-3.columns
  =form_tag root_path do
    =text_field_tag "q", params[:q]
    =submit_tag "Search"

    .panel#side-nav
      %h5
        %bold Categories
      %ul#categories
        -CATEGORIES.get_categories.each do |root|
          %li
            =label_tag root.tag,root.title, {:class=>("off" unless category_on?(params['categories'],root.tag))}
            =check_box_tag "categories[]", root.tag,category_on?(params['categories'],root.tag),{:id=>root.tag,:class=>"category root hidden"}
            %ul.subcategories
              -root.children.each do |child|
                %li
                  =label_tag child.tag,child.title,{:class=>("off" unless category_on?(params['categories'],child.tag))}
                  =check_box_tag "categories[]", child.tag, category_on?(params['categories'],child.tag),{:id=>child.tag,:class=>"category child hidden"}
          -unless CATEGORIES.get_categories.last == root 
            %hr

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :link
    = f.text_field :link
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/posts/_post.html.haml
/ Feed Entry
.row.post{:id=>"post-#{post.id}"}
  .large-9.columns.small-9.title
    %h5
      =link_to raw(post.title), post.link, :target=>"_blank"
  .large-3.columns.small-3.dev-name
    -if post.dev
      %h5
        =link_to post.dev.name, root_path(:dev=>post.dev.id)

  .large-12.columns.fp-post
    = link_to "Click to Show First Post", first_post_post_path(post)

  .large-12.columns.description
    %p= raw post.description
  .large-4.columns.utc-date
    = post.published_at
  .large-8.columns.categories
    = post.categories.join(",")

%hr
/ End Feed Entry

app/views/posts/_stream.html.haml
- unless posts.empty?
  =render :partial => "post", :collection=>posts        
  #load-more.large-12.column
    -params[:page] = params[:page] ? (params[:page].to_i + 1) : 2
    =link_to "Load More Posts!", root_path(params)

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
.row
  / Nav Sidebar
  / This is source ordered to be pulled to the left on larger screens
  =render :partial => "categories_sidebar"
  /Main List
  .large-9.columns#stream
    =render :partial => "stream", :locals=>{:posts=>@posts}

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @post.title
%p
  %b Link:
  = @post.link
%p
  %b Description:
  = @post.description

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path

app/views/shared/_logo_bar.html.haml
/ Header and Nav
%nav.top-bar
  %ul.title-area
    %li.name
      %h1
        %a{:href => "/"}
          DevChaser
  %section.top-bar-section
    / Left Nav Section
    %ul.left
    / Right Nav Section
    %ul.right
      %li.divider
      %li
        =link_to "GW2 Dev Tracker", "https://forum-en.guildwars2.com/forum/info/devtracker", :target=>"_blank"
/ End Header and Nav